### ISSUE TITLE
Signing within Unity

### ISSUE THREAD

**Issue by AdonousTech** [Desonity/Desonity#1]
*Hey, my DESO handle is @mattpitts.*

Have you looked at the following plugin for solving the "login and sign txns directly in Unity" issue?

https://developer.vuplex.com/webview/overview

According to the following article, the plugin 3d WebView has a "message passing API" (https://support.vuplex.com/articles/how-to-send-messages-from-javascript-to-c-sharp).

With this plugin it *should* be possible to 1) use a basic HTML page with a single IFRAME which loads the DESO Identity window; 2) use the [native HTML5 Window.PostMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send messages between the html page and DESO Identity; 3) pass the message further to C# via the window.vuplex.postMessage api which actually mimics the window.postMessage API.

If it's a matter of cost, I am willing to purchase a license for the plugin for you to develop with and use how you like. I think this is the solution to take Desonity to the next level!

**Comment by ankushKun** [comment]
Hi Matt,

Thank you so much for reaching out and supporting the project,
I did come across the vuplex webview plugin before, and you're correct, it could be used to make unity communicate with deso identity through the postMessage process, which will smooth out the login process very much for the users.

The reason why I did not use vuplex was mainly because of course the pricing, and as it is a paid asset, I am not sure how should I bundle it with Desonity, since Desonity will be opensource, I don't know if it's okay to provide a paid asset for free with an opensource project (legal issues?).

PS. Signing is supported within Unity now, an external webapp is used only for login/making derived keys which is a one time process until the user logs out (similar to games which open a browser window for login).

Let me know what you think.

**Comment by AdonousTech** [comment]
Hi Ankush, 

Ah, I understand now. Yes, it makes sense to only use software with the same or similar license as Desonity.

"PS. Signing is supported within Unity now, an external webapp is used only for login/making derived keys which is a one time process until the user logs out (similar to games which open a browser window for login)."

Ok, so I'm interested in that part. It seems perfectly acceptable to route the user to a separate endpoint to start the authentication flow. 

After the user obtains a derived key, then what? Do you redirect back to the Unity app? How do you test that flow during development? Does Unity listen on a specific port? I'm still in the process of getting up to speed on Unity, but I am fluent in .Net (VB.Net and C#).

**Comment by ankushKun** [comment]
The user is sent to a webpage when they are shown the name of the application that asked for login and if they want to derive keys(full access) or login with access level 2(can't make transactions).

Unity makes a post request to the webpage every 3 seconds until the user has logged in (max 2 minutes) and gets their keys in response.

I really want to change this and somehow make the webpage send the keys to Unity, without Unity having to make requests continuously, so I could use some help here.

The keys can then be encrypted and stored for future use.

Here is a video demonstrating login
https://diamondapp.com/posts/259ab5d8f98243b1afafea59fc86b265addd171c4431470e59a8f55b748e0761

Here is a video demonstrating login and buying a creator coin
https://diamondapp.com/posts/8c6511573630c3c1c102a82eb8f48ef3460a3dc2821ba564843c1fdf63891265

**Comment by AdonousTech** [comment]
I see. I assume you're persisting the key somewhere (db?) before its returned to Unity when polled? What's your solution for ensuring your backend returns the appropriate key to Unity for the active session?

An alternative implementation could be web sockets. https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API  However, I'm not sure that fully solves the problem. Websockets will allow incoming messages to Unity, but the initial connection (login, keymaterial) must be made, nonetheless. There are some benefits there, but nothing game changing.

I did some brief research and found this article regarding implementation of a websocket client/server. with Unity and C#.
https://medium.com/unity-nodejs/websocket-client-server-unity-nodejs-e33604c6a006

**Comment by ankushKun** [comment]
The unity session generates a uuid v4 key which is sent to the server, and only the deso keys associated with that uuid is returned to unity.

This SO answer explains how unique uuid v4 are
https://stackoverflow.com/a/1155027/11970087

edit: the uuid and deso keys are also removed from the backend after sending them to Unity

**Comment by AdonousTech** [comment]
Got it! Thanks for the explanations, and your work on this. I hope to implement this as the main library for facilitating communication between DeSo and Unity applications.

I was thinking about web sockets because I plan on implementing a "lobby" where users will effectively authenticate before entering a specific Unity application (there will be many). The idea is for all Unity applications to share a common communication subsystem, alleviating the need to initiate authentication for each application. Web sockets also allow duplex communication between the authentication app ("lobby") and the "active" Unity application.

Web sockets help keep everything DRY.

I think you're on the right track with the UUID that establishes the session. However, I would want to do that in the "lobby". When a Unity application is subsequently launched (we'll know because the user has to click to enter the application from the lobby), we can "initialize" the system with the appropriate "global" session Id which is internally linked in a 1:1 with the user's derived key. We can then send that "global" session Id and associated derived key to Unity. Before the Unity application exits, it can send a message to the "lobby" requesting disconnection of the messaging channel.

The pattern above facilitates communication between DeSo and Unity, but can also be used to facilitate duplex communication between Unity and other backend systems in a systematic way. Without web sockets, we'll need to write code for every type of networked connection.

It would be great to update Desonity with web sockets. However, its your project and I will leave it up to you! Thanks again for the explanations and the work on this project!
